---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=helloWorld&var-version=1.0.0-SNAPSHOT
  labels:
    app: helloWorld
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.tibco.bw
  name: bwce-sample
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloWorld
      provider: fabric8
      group: com.tibco.bw
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=helloWorld&var-version=1.0.0-SNAPSHOT
      labels:
        container: bwce-sample
        project: bwce-sample
        app: helloWorld
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: com.tibco.bw
      name: bwce-sample
      namespace: default
    spec:
      containers:
      - env:
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: BW_LOGLEVEL
          value: DEBUG
        - name: BW_PROFILE
          value: docker
        image: gcr.io/gcpbwcepoc/hello-world-rest-api:v1
        imagePullPolicy: Always
        name: bwce-sample
        ports:
        - containerPort: 8080
          name: http
