metadata:
  name: bwce-sample
kind: Deployment
spec:
  template:
    metadata:
      name: bwce-sample
      namespace: default
      labels:
        container: bwce-sample
        project: bwce-sample
    spec:
      containers:
      - image: gcr.io/gcpbwcepoc/hello-world-rest-api:v1
        imagePullPolicy: Always
        name: bwce-sample
        env:
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: BW_LOGLEVEL
          value: DEBUG
        - name: BW_PROFILE
          value: docker
        ports:
        - containerPort: 8080
  replicas: 1
  selector:
    container: bwce-sample
    provider: fabric8
    project: bwce-sample
    group: com.tibco.bw
